//create user

POST http://localhost:5000/users
Content-Type: application/json

{
    "name" :"M Fikri",
    "email":"admin@gmail.com",
    "password":"123456",
    "confPassword":"123456",
    "role":"admin"
}
###
//GET ALL Users 
GET http://localhost:5000/users

###
GET http://localhost:5000/users/536729cb-58a3-4d28-8a3a-a319ec5b9da1

###
PATCH  http://localhost:5000/users/536729cb-58a3-4d28-8a3a-a319ec5b9da1
Content-Type: application/json

{
    "name" :"M Safikru",
    "email":"admin@gmail.com",
    "password":"123",
    "confPassword":"123",
    "role":"admin"
}
###

DELETE   http://localhost:5000/users/536729cb-58a3-4d28-8a3a-a319ec5b9da1

//login
###
POST http://localhost:5000/login
Content-Type: application/json

{
    
    "email":"admin@gmail.com",
    "password":"123456",
    
}